version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.33.4
    ports:
    - 9090:9090
    volumes:
    - prometheus_data:/prometheus
    - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=30d'


  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100

  alertmanager:
    image: prom/alertmanager
    ports:
    - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  blackbox:
    image: prom/blackbox-exporter:master
    ports:
    - 9115:9115
    volumes:
      - ./blackbox/:/config/
    command:
      - '--config.file=/config/blackbox.yml'    

#  dingdingtalk:
#    image: timonwong/prometheus-webhook-dingtalk
#    ports:
#    - 8060:8060
#    volumes:
#    - ./webhook/:/

  grafana:
    image: grafana/grafana
    user: '472'
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana 
